# Generated by Django 5.0.6 on 2024-10-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="date", field=models.DateTimeField(auto_now=True),
        ),
    ]
